
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lucas
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     * @throws java.sql.SQLException
     */
    public Registration() throws SQLException {
        initComponents();
        autoID();
        table_update();
    }
    
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        txtcost = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        edit_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        txtavl = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtsuspension = new javax.swing.JComboBox<>();
        txtframe = new javax.swing.JComboBox<>();
        txttire = new javax.swing.JComboBox<>();
        txtwheelsize = new javax.swing.JComboBox<>();
        txtweight = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bicycle registration"));

        jLabel1.setText("Bicycle ID");

        jLabel2.setText("Model");

        jLabel3.setText("Base cost per hour");

        jLabel4.setText("Available");

        txtcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcostKeyPressed(evt);
            }
        });

        add_button.setBackground(new java.awt.Color(0, 153, 255));
        add_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setText("Add");
        add_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        edit_button.setBackground(new java.awt.Color(0, 153, 255));
        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(0, 153, 255));
        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        txtavl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        jLabel5.setText("Quantity");

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_button)
                    .addComponent(edit_button))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtmodel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcost, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtavl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtquantity))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtavl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edit_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delete_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_button)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Model", "Cost", "Available", "Suspension", "Frame", "Tire", "WheelSize", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Bicycle components");

        txtsuspension.setBackground(new java.awt.Color(204, 51, 0));
        txtsuspension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select suspension", "Hardtail", "Full Suspension", "None" }));

        txtframe.setBackground(new java.awt.Color(204, 51, 0));
        txtframe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frame", "Aluminum", "Carbon Fiber", "Steel" }));

        txttire.setBackground(new java.awt.Color(204, 51, 0));
        txttire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tire TPI rating", "30", "60", "120", "250", "320" }));

        txtwheelsize.setBackground(new java.awt.Color(204, 51, 0));
        txtwheelsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wheel Size (inches)", "29", "27", "26", " " }));
        txtwheelsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwheelsizeActionPerformed(evt);
            }
        });

        txtweight.setMajorTickSpacing(1);
        txtweight.setMaximum(30);
        txtweight.setMinimum(10);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Weight (min=10kg)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtsuspension, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtframe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtwheelsize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsuspension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtwheelsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        String bikeID = txtID.getText();
        String model = txtmodel.getText();
        String suspension = "";
        String frame = "";
        int tireTPI=0;
        int wheelsize=0;
        if(bikeID.isBlank() || model.isBlank() || txttire.getSelectedIndex()==0 || txtwheelsize.getSelectedIndex()==0){
            //handling validation failure
            JOptionPane.showMessageDialog(this, "All fields are required");
            return;
        }
        if(txtsuspension.getSelectedIndex() !=0){suspension = txtsuspension.getSelectedItem().toString();}
        if(txtframe.getSelectedIndex() !=0){frame = txtframe.getSelectedItem().toString();}
        if(txttire.getSelectedIndex()!=0){ tireTPI = Integer.valueOf(txttire.getSelectedItem().toString());}
        if(txtwheelsize.getSelectedIndex()!=0){wheelsize = Integer.valueOf(txtwheelsize.getSelectedItem().toString());}
        int weight = (int)txtweight.getValue();
        int cost = Integer.parseInt(txtcost.getText());
        int intavl = txtavl.getSelectedIndex();
        boolean avl = (intavl !=0);
        int quantity = Integer.parseInt(txtquantity.getText());
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bikerent","root","");
            pst = con.prepareStatement("insert into registration(bikeID,model,cost,available,suspension,frame,tireTPI,wheelSize,weight) values(?,?,?,?,?,?,?,?,?)");
            for(int i=0;i<quantity;i++){
                pst.setString(1, bikeID);
                pst.setString(2, model);
                pst.setInt(3, cost);
                pst.setBoolean(4, avl);
                pst.setString(5, suspension);
                pst.setString(6, frame);
                pst.setInt(7, tireTPI);
                pst.setInt(8, wheelsize);
                pst.setInt(9, weight);
                pst.executeUpdate();
                String numericpart = bikeID.substring(1);
                int num = Integer.parseInt(numericpart);
                num++;
                bikeID = bikeID.substring(0, 1) + String.format("%04d", num);
            }
            JOptionPane.showMessageDialog(this, quantity + " bicycles of model " + model + " successfully added");
            txtmodel.setText("");
            txtcost.setText("");
            txtquantity.setText("");
            txtavl.setSelectedIndex(-1);
            txtmodel.requestFocus();
            table_update();
            autoID();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_add_buttonActionPerformed

    private void txtcostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostKeyPressed
        // TODO add your handling code here:
   
        if(evt.getKeyChar() >='0' && evt.getKeyChar()<='9'){
            txtcost.setEditable(true);
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtcost.setEditable(true);
            }
            else{
                txtcost.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtcostKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        txtID.setText(d1.getValueAt(selectIndex, 0).toString());
        txtmodel.setText(d1.getValueAt(selectIndex, 1).toString());
        txtcost.setText(d1.getValueAt(selectIndex, 2).toString());
        txtavl.setSelectedItem(d1.getValueAt(selectIndex, 3));
        //assigning values to dropdown boxes
        JComboBox[] comboboxes = {txtsuspension, txtframe, txttire, txtwheelsize};
        String[] inputs = {(d1.getValueAt(selectIndex, 4).toString()),(d1.getValueAt(selectIndex, 5).toString()),
            (d1.getValueAt(selectIndex, 6).toString()), (d1.getValueAt(selectIndex, 7).toString())};
        System.out.println(1);
        for(int i=0;i<comboboxes.length; i++){
            JComboBox comboBox = comboboxes[i];
            String input = inputs[i];
            System.out.println(i);
            
            for(int j=1;j<comboBox.getItemCount()-1; j++){
                if(comboBox.getItemAt(j).equals(input)){
                    comboBox.setSelectedIndex(j);
                    break;
                }
            }
        }
        System.out.println(2);
        txtweight.setValue(Integer.parseInt(d1.getValueAt(selectIndex, 8).toString()));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        try {
            String id = d1.getValueAt(selectIndex, 0).toString();
            String model = txtmodel.getText();
            int cost = Integer.parseInt(txtcost.getText());
            int intavailability = txtavl.getSelectedIndex();
            boolean availability = (intavailability !=0);
            String suspension = txtsuspension.getSelectedItem().toString();
            String frame = txtframe.getSelectedItem().toString();
            int tireTPI = Integer.parseInt( (String) txttire.getSelectedItem());
            int wheelSize = Integer.parseInt( (String) txtwheelsize.getSelectedItem());
            int weight = txtweight.getValue();

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bikerent","root","");
            
            pst = con.prepareStatement("update registration set model=?,cost=?,available=?,suspension=?,frame=?,tireTPI=?,wheelSize=?,weight=? where bikeID = ?");
            
            pst.setString(1, model);
            pst.setInt(2, cost);
            pst.setBoolean(3, availability);
            pst.setString(4, suspension);
            pst.setString(5, frame);
            pst.setInt(6, tireTPI);
            pst.setInt(7, wheelSize);
            pst.setInt(8, weight);
            pst.setString(9, id);
    
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record sucessfully updated ");
            table_update();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        
            String id = d1.getValueAt(selectIndex, 0).toString();
            int dialogResult = JOptionPane.showConfirmDialog(this, "This record will be deleted permanently.","WARNING",JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION){
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/bikerent","root","");
                pst = con.prepareStatement("delete from registration where bikeID = ?");
                pst.setString(1, id);
                pst.executeUpdate();
                table_update();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            }
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtwheelsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwheelsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwheelsizeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void table_update(){
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bikerent","root","");
            pst = con.prepareStatement("select * from registration");
            ResultSet Rs = pst.executeQuery();
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel d1 = (DefaultTableModel)jTable1.getModel();
            d1.setRowCount(0);
            
            while(Rs.next()){
                Vector v2 = new Vector();
                for(int i=1;i<c;i++){
                    v2.add(Rs.getString("bikeID"));
                    v2.add(Rs.getString("model"));
                    v2.add(Rs.getInt("cost"));
                    v2.add(Rs.getString("available"));
                    v2.add(Rs.getString("suspension"));
                    v2.add(Rs.getString("frame"));
                    v2.add(Rs.getString("tireTPI"));
                    v2.add(Rs.getString("wheelSize"));
                    v2.add(Rs.getString("weight"));
                }
                d1.addRow(v2);
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
            
    
    
    
    
 
    public void autoID() throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/bikerent","root","");
            Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select Max(bikeID) from Registration");
            rs.next();
            rs.getString("Max(bikeID)");
            
            if( rs.getString("Max(bikeID)") == null){
                txtID.setText("B0001");
            }
            else{
                long id = Long.parseLong(rs.getString("Max(bikeID)").substring(2,rs.getString("Max(bikeID)").length()));
                id++;
                txtID.setText("B0" + String.format("%03d",id));
            }
                    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Registration().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton back_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtID;
    private javax.swing.JComboBox<String> txtavl;
    private javax.swing.JTextField txtcost;
    private javax.swing.JComboBox<String> txtframe;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JComboBox<String> txtsuspension;
    private javax.swing.JComboBox<String> txttire;
    private javax.swing.JSlider txtweight;
    private javax.swing.JComboBox<String> txtwheelsize;
    // End of variables declaration//GEN-END:variables
}
